### ISSUE TITLE
Is the file deletion obligatory?

### ISSUE THREAD

**Issue by PhilVince96** [kstrafe/file-rotate#26]
I want the timestamp suffix with an hourly rotation as ContentLimit::Time and I can only choose between AppendTimestamp(FileLimit::MaxFile(usize)) and AppendTimestamp(FileLimit::Age(Duration)).
From the documentation I am not sure if I can opt out of deleting.
And one more question: Is the first file always written without the timestamp?

**Comment by Ploppz** [comment]
I'm adding a `FileLimit::Unlimited`. Will publish soon.

The first file is indeed always written without a suffix/timestamp. It gets the suffix when it is rotated. So in the case of timestamp suffix, the suffix signifies the _last_ time of writing.

**Comment by Ploppz** [comment]
It was published btw, as 0.7.6.
Please feel free to continue the discussion about suffix on the current file, perhaps in a new issue.
